### ISSUE TITLE
 Software center doesn't start + No brightness adjustment + Xiwi target for extension ?

### ISSUE THREAD

**Issue by seanw712** [jeremy-breidenbach/MyDearFreya#1]
Hi,

I can't seem to open the software center, any fix on this? Did I miss something?
A minor issue too: can't adjust screen brightness in elementary, not in settings, not with the shortkeys...
I was also wondering if I could use this in combination with the Crouton extension, so I can open it in tabs?
Anyways, thanks for the great work, Elementary looks fabulous!

Sean

---

Running a Toshiba Chromebook 2 with Celeron processor

**Comment by seanw712** [comment]
I got the software center fixed, sorry, didnt read your readme very thoroughly..... However, I do still get a lot of FCs/errors, is this normal on this release?

**Comment by jeremy-breidenbach** [comment]
Hi @seanw712 , I do also get a lot of errors. The elementary OS script is from Reddit user Skitals (link at the top of the README), so thanks definitely goes to Skitals for creating the script. I am hoping to look into some of the errors and adjust the script as needed. 

So far I have only had luck adjusting the brightness in elementary OS by typing these commands in the terminal: 
`brightness up`
`brightness down`

You should be able to use this with the extension, I believe you just have to update the chroot and add the new target. Here's the command from the Crouton cheat sheet, replace **chrootname** with **freya**:
Update a chroot while adding new target(s): sudo sh ~/Downloads/crouton -u -n **chrootname** -t targets_you_want_to_install_separated_by_commas

**Comment by seanw712** [comment]
Thanks a lot!
Op 5-jan.-2016 05:06 schreef "Jeremy Breidenbach" <notifications@github.com
