### ISSUE TITLE
Unable to Start Chroot with 'startelementary'

### ISSUE THREAD

**Issue by saeedted** [jeremy-breidenbach/MyDearFreya#2]
Whenever I type the command 'startelementary' command I see the message "/mnt/stateful_partition/crouton/chroots/watson not found" in red. I will delete chroot and start again to see if there is a difference; download was 2.1gb!

**Comment by jeremy-breidenbach** [comment]
@saeedted did you previously try installing elementary OS via a different method? The script in this github repo automatically names the chroot "freya," but it looks like your startelementary command is looking for a chroot named "watson." Is it possible there was already a "startelementary" script in your crouton, or did you start completely fresh from developer mode?

**Comment by saeedted** [comment]
i did install nstalling elementary OS via the mydearwatson script. then i tried to upgrade to freya within the os which ended in disaster. should i powerwash then run mydearfreya?

**Comment by saeedted** [comment]
@jeremy-breidenbach good news, installation succeeded after i powerwashed. But now whenever I switch from freya back to chrome the trackpad stops working until i close freya with ctrl+c. any ideas on a workaround?

**Comment by jeremy-breidenbach** [comment]
@saeedted great to hear you got it working after the powerwash! I haven't experienced that trackpad issue, but I googled the issue and found a [reddit thread](https://www.reddit.com/r/Crouton/comments/3k4f0s/mouse_pointerkeyboard_not_working_after_switching/) regarding the exact same issue with Crouton/elementary OS Freya. They got it working by doing the following: 
1. In elementary run sudo chown -R $USER:$USER /home/$USER/.config
2. In system settings (in elementary) make sure that "disable trackpad while typing" is disabled
3. Logout of elementary, log back in.

Can you try these steps?

**Comment by saeedted** [comment]
Trackpad works! You already have that command in the readme.md file which I needed to save settings (otherwise I wouldn't be able to save my keyboard layout) so I guess I just needed to be patient. 

Now I'll just back this chroot to my sd card and see about adding chrome os's volume and brightness keys and adding an X11 intergration. Thanks for your help and work @jeremy-breidenbach
